### ISSUE TITLE
UI non interactable once download starts, can not cancel

### ISSUE THREAD

**Issue by HellishINC** [jahendrie/qytdl#5]
(Sorry for bugging you so much)

Once you start the download process, the UI becomes non-responsive to any user input. For example, you can not add new links. There also appears to be no way to cancel (or pause) downloads once started besides killing the process.

**Comment by jahendrie** [comment]
Don't worry about it, I'll admit I've been neglecting this a tad.

Anyway, the behavior described is functioning as "intended", as I've never personally felt the need to do either of those things you've mentioned with this (you'll notice there isn't even a cancel button).  I can go ahead and try to implement those in the near future, however.  Particularly the add-as-you-go thing seems like a decent idea.

**Comment by HellishINC** [comment]
Feel free to close this issue if you do indeed decide `feature not a bug`.
